// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:820339099312:web:a484d267eccc821e8e9d75',
    messagingSenderId: '820339099312',
    projectId: 'vichack-4ea1e',
    authDomain: 'vichack-4ea1e.firebaseapp.com',
    storageBucket: 'vichack-4ea1e.appspot.com',
    measurementId: 'G-EEK0RVBMG9',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCls67yIqY6ozRWvdQ-wxNsRBojZ7PEEEk',
    appId: '1:820339099312:web:dbbafa511a116e118e9d75',
    messagingSenderId: '820339099312',
    projectId: 'vichack-4ea1e',
    authDomain: 'vichack-4ea1e.firebaseapp.com',
    storageBucket: 'vichack-4ea1e.appspot.com',
    measurementId: 'G-SFD82L3XP8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9QYbBwAcjbxGKD5ty6qYpwpiUVWKUubw',
    appId: '1:820339099312:ios:e269b51b7ea3ec088e9d75',
    messagingSenderId: '820339099312',
    projectId: 'vichack-4ea1e',
    storageBucket: 'vichack-4ea1e.appspot.com',
    iosBundleId: 'com.example.vicHackMobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9QYbBwAcjbxGKD5ty6qYpwpiUVWKUubw',
    appId: '1:820339099312:ios:e269b51b7ea3ec088e9d75',
    messagingSenderId: '820339099312',
    projectId: 'vichack-4ea1e',
    storageBucket: 'vichack-4ea1e.appspot.com',
    iosBundleId: 'com.example.vicHackMobile',
  );

}
