// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiZyY1WrQ8Gbun-o9vWDw_DF6KJcEng4M',
    appId: '1:236974795343:web:d4beff1439c21d3c70183a',
    messagingSenderId: '236974795343',
    projectId: 'vichackmobile',
    authDomain: 'vichackmobile.firebaseapp.com',
    storageBucket: 'vichackmobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClE8_8DaD7NrUKLfL6InJyz4ioroQOVUE',
    appId: '1:236974795343:android:7d77cc8c548af65e70183a',
    messagingSenderId: '236974795343',
    projectId: 'vichackmobile',
    storageBucket: 'vichackmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhBBY0mUfwfbus825U-1Bj-WzimTmH0jU',
    appId: '1:236974795343:ios:7e48af283ea4693770183a',
    messagingSenderId: '236974795343',
    projectId: 'vichackmobile',
    storageBucket: 'vichackmobile.appspot.com',
    iosBundleId: 'com.example.vicHackMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhBBY0mUfwfbus825U-1Bj-WzimTmH0jU',
    appId: '1:236974795343:ios:7e48af283ea4693770183a',
    messagingSenderId: '236974795343',
    projectId: 'vichackmobile',
    storageBucket: 'vichackmobile.appspot.com',
    iosBundleId: 'com.example.vicHackMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiZyY1WrQ8Gbun-o9vWDw_DF6KJcEng4M',
    appId: '1:236974795343:web:bd3964e45f498b0570183a',
    messagingSenderId: '236974795343',
    projectId: 'vichackmobile',
    authDomain: 'vichackmobile.firebaseapp.com',
    storageBucket: 'vichackmobile.appspot.com',
  );
}
